package work.ganglia.port.internal.hook;

import io.vertx.core.Future;
import work.ganglia.infrastructure.external.tool.model.ToolInvokeResult;
import work.ganglia.port.chat.Message;
import work.ganglia.port.chat.SessionContext;
import work.ganglia.port.external.tool.ToolCall;

/**
 * Interface for intercepting the Agent's lifecycle (Turns and Tool Executions). Hooks can be used
 * for memory injection, security checks, output compression, or logging.
 */
public interface AgentInterceptor {

  /**
   * Phase 1: Before the Agent processes the user's input. Use case: Semantic search for historical
   * memories and injecting them into the Context. Return a failed Future to abort the turn.
   *
   * @param context Current session context
   * @param userInput The raw user input text
   * @return The possibly modified SessionContext (e.g., with extra context fragments)
   */
  default Future<SessionContext> preTurn(SessionContext context, String userInput) {
    return Future.succeededFuture(context);
  }

  /**
   * Phase 2: Before a specific tool is executed. Use case: Permission validation, argument
   * sanitization. Return a failed Future (e.g., SecurityException) to abort the tool execution.
   *
   * @param call The tool call requested by the LLM
   * @param context Current session context
   * @return The possibly modified ToolCall
   */
  default Future<ToolCall> preToolExecute(ToolCall call, SessionContext context) {
    return Future.succeededFuture(call);
  }

  /**
   * Phase 3: After a tool has executed, before returning the result to the LLM. Use case: Long
   * output compression (ObservationCompressor), filtering sensitive data. Return a failed Future to
   * simulate a tool error.
   *
   * @param call The tool call that was executed
   * @param result The raw result from the ToolExecutor
   * @param context Current session context
   * @return The possibly modified ToolInvokeResult
   */
  default Future<ToolInvokeResult> postToolExecute(
      ToolCall call, ToolInvokeResult result, SessionContext context) {
    return Future.succeededFuture(result);
  }

  /**
   * Phase 4: After the turn is completed and the final response is generated. Use case: Background
   * reflection, extracting new knowledge, summarizing the turn. Note: This hook should typically
   * run asynchronously and not block the user response. If this Future fails, it will only be
   * logged, it will NOT crash the agent loop.
   *
   * @param context The session context containing the full history of this turn
   * @param finalResponse The final message/response generated by the agent
   */
  default Future<Void> postTurn(SessionContext context, Message finalResponse) {
    return Future.succeededFuture();
  }
}
